# Generated by Django 3.1.4 on 2020-12-18 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0002_response'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='isTaking',
            new_name='isTaken',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='time_taking',
            new_name='time_taken',
        ),
    ]
